### ISSUE TITLE
Scheduler for requests and tokens?

### ISSUE THREAD

**Issue by MaciejIwan** [innowacja2022-dapp-TTPSC/TTPSC-App#20]
I think it is good idea to implement expiration date (timeout) for each request using "https://github.com/OpenZeppelin/openzeppelin-eth/blob/master/contracts/Schedule.sol";

Maybe tokens also should have expirationdate? For example employee could store token for 1 year. And after 1 year tokens will back owner account.

**Comment by bofomike** [comment]
Provided link doesn't work any more: 
https://github.com/OpenZeppelin/openzeppelin-eth/blob/master/contracts/Schedule.sol
