### ISSUE TITLE
Add Admin panel

### ISSUE THREAD

**Issue by MrDell1** [innowacja2022-dapp-TTPSC/TTPSC-App#33]

**Comment by MrDell1** [comment]
![image](https://user-images.githubusercontent.com/33961381/213742117-2377bd5f-6251-4a12-a4e5-871d9dfabae8.png)

**Comment by matiduda** [comment]
https://github.com/innowacja2022-dapp-TTPSC/TTPSC-Rewards-DApp/pull/41
