### ISSUE TITLE
Add small Menu when user click on his/her address

### ISSUE THREAD

**Issue by MrDell1** [innowacja2022-dapp-TTPSC/TTPSC-App#35]

**Comment by MrDell1** [comment]
![image](https://user-images.githubusercontent.com/33961381/213737044-9dc28af7-7e7e-4ab5-81d0-82bf47b81666.png)

* Avatar with badge: https://chakra-ui.com/docs/components/avatar/usage#avatar-with-badge
* Modal: https://chakra-ui.com/docs/components/modal/usage#control-focus-when-modal-closes

**Comment by matiduda** [comment]
https://github.com/innowacja2022-dapp-TTPSC/TTPSC-Rewards-DApp/pull/42
